spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
